FROM node:8-jessie as builder
RUN npm install -g yarn
WORKDIR /build

COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY . .

RUN yarn build

# arm nginx sha - nginx 1.17.6-alpine
FROM nginx@sha256:2ba87319e603f89471a23b95f90d1635df8e5b7366c65afdda9228b3ffb4528d
COPY --from=builder /build/dist /usr/share/nginx/html
